name: Deploy VitePress to GitHub Pages

on:
  # 當推送到 main 分支時觸發
  push:
    branches: [ main ]
  # 允許手動觸發
  workflow_dispatch:

# 設定權限
permissions:
  contents: read
  pages: write
  id-token: write

# 確保只有一個部署在進行
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # 建構工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出代碼
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 需要完整歷史以便 VitePress 生成最後修改時間
          
      - name: 設定 Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          
      - name: 設定 Pages
        uses: actions/configure-pages@v4
        
      - name: 安裝依賴
        run: npm ci
        
      - name: 建構 VitePress
        run: npm run docs:build
        
      - name: 上傳建構結果
        uses: actions/upload-pages-artifact@v3
        with:
          path: .vitepress/dist

  # 部署工作
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4